%% Global Variables
-define(FIND_ALL, 3).
-define(REPLACE_ALL, 5).
-define(REPLACE_FIND, 6).
-define(FIND_NEXT, 7).
-define(FIND_PREV, 9).
-define(FIND_INPUT, 10).
-define(REPLACE_INPUT, 11).
-define(IGNORE_CASE, 1).
-define(WHOLE_WORD, 2).
-define(START_WORD, 4).
-define(REGEX, 8).
-define(FIND_LOC, 12).
-define(FIND_LOC_DOC, 0).
-define(FIND_LOC_PROJ, 1).
-define(FIND_LOC_OPEN, 2).
